=== Velc97/Millennium-games/SchemaCommenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="COMMENTI">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="sezioneCommentiGioco" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


	<xs:element name="sezioneCommentiGioco">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="commento" maxOccurs="unbounded" minOccurs="0" type="TipoCommento"/>
			</xs:sequence>
        <xs:attribute name="idGioco" type="xs:integer"/>
		</xs:complexType>
	</xs:element>

    <xs:complexType name="TipoCommento">
        <xs:sequence>
            <xs:element name="utente" type="xs:string"/>
            <xs:element name="testo" type="xs:string"/>
            <xs:element name="recensione" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    <xs:attribute name="commentoCancellato" type="xs:string"/>
    </xs:complexType>


</xs:schema>

=== Velc97/Millennium-games/SpecificaDatiCommenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<COMMENTI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SchemaCommenti.xsd">

    <sezioneCommentiGioco idGioco="31">
        <commento commentoCancellato="NO">
            <utente>CosmoVellucci</utente>
            <testo>Questo gioco e' molto bello!</testo>
            <recensione>P</recensione>
        </commento>
        <commento commentoCancellato="NO">
            <utente>Arturo</utente>
            <testo>Concordo pienamente con te Cosmo. E' eccezionale.</testo>
            <recensione></recensione>
        </commento>
        <commento commentoCancellato="SI">
            <utente>Manigoldo</utente>
            <testo>QUESTO COMMENTO E' CANCELLATO.</testo>
            <recensione></recensione>
        </commento>
        <commento commentoCancellato="NO">
            <utente>CosmoVellucci</utente>
            <testo>Ti ringrazio, caro Arturo.</testo>
            <recensione></recensione>
        </commento>
    </sezioneCommentiGioco>

    <sezioneCommentiGioco idGioco="2">
    </sezioneCommentiGioco>

    <sezioneCommentiGioco idGioco="25">
    </sezioneCommentiGioco>

    <sezioneCommentiGioco idGioco="77">
    </sezioneCommentiGioco>

</COMMENTI>
